[install]
exact = true
minimumReleaseAge = 86400
minimumReleaseAgeExcludes = [
  "@jsr/mkvlrn__app-error",
  "@mkvlrn/app-eror",
  "@jsr/mkvlrn__config",
  "@mkvlrn/config",
  "@jsr/mkvlrn__result",
  "@mkvlrn/result",
]


[test]
coveragePathIgnorePatterns = ["tests/**", "infra/**"]
