FROM oven/bun:1.3.14-alpine

WORKDIR /var/task
ENV PORT=3000

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.0.1 /lambda-adapter /opt/extensions/lambda-adapter
COPY package.json bun.lock* bunfig.toml ./
RUN bun install --frozen-lockfile --ignore-scripts --production
COPY . .

ENTRYPOINT ["bun", "src/main.ts"]
