[commit-msg.commands]
cog-lint = { run = "cog verify --file {1}" }

[pre-commit.commands]
typecheck = { glob = "*.{ts,tsx}", run = "mise typecheck" }
lint = { glob = "*.{ts,tsx,json,jsonc}", run = "mise lint {staged_files}" }
test = { glob = "*.{ts,tsx}", run = "mise test-staged" }

[pre-push.commands]
typecheck = { run = "mise typecheck" }
lint = { run = "mise lint" }
test = { run = "mise test-ci" }

[post-checkout]
piped = true

[post-checkout.commands]
1_sync-mise = { run = "mise install" }
2_clean-mise = { run = "mise prune -y" }
3_sync-bun = { run = "bun install --frozen-lockfile" }
4_sync-githooks = { run = "lefthook install" }

[post-merge]
piped = true

[post-merge.commands]
1_sync-mise = { run = "mise install" }
2_clean-mise = { run = "mise prune -y" }
3_sync-bun = { run = "bun install --frozen-lockfile" }
4_sync-githooks = { run = "lefthook install" }
