[commit-msg.commands]
commitlint = { run = "mise run commitlint {1}" }

[pre-commit.commands]
typecheck = { glob = "*.{ts,tsx}", run = "mise run typecheck" }
lint = { glob = "*.{ts,tsx,json,jsonc}", run = "mise run lint -- {staged_files}" }
test = { glob = "*.{ts,tsx}", run = "mise run test-staged" }

[pre-push.commands]
typecheck = { run = "mise run typecheck" }
lint = { run = "mise run lint" }
test = { run = "mise run test-ci" }

[post-checkout.commands]
sync = { run = "mise run sync-branch" }

[post-merge.commands]
sync = { run = "mise run sync-branch" }
