[tools]
biome = "2.5.6"
bun = "1.3.14"
cocogitto = "7.0.0"
"github:pulumi/pulumi" = "3.255.0"
lefthook = "2.1.10"

[env]
_.path = ["./node_modules/.bin"]

[settings]
disable_backends = ["asdf"]
use_versions_host = false
minimum_release_age = "1d"

[tasks.dev]
description = "Dev mode"
run = "bun --watch src/main.ts"
[tasks.lint]
description = "Check files with biome"
run = "biome check --diagnostic-level=warn --no-errors-on-unmatched"
[tasks.lint-fix]
description = "Fix files with biome"
run = "biome check --diagnostic-level=warn --no-errors-on-unmatched --write"
[tasks.typecheck]
description = "Run tsc"
run = "tsc"
[tasks.test]
description = "Run tests"
run = "bun test --coverage"
[tasks.test-staged]
description = "Run tests on staged files"
run = "bun test --changed --bail --reporter=dots"
[tasks.test-ci]
description = "Run tests in ci mode"
run = "bun test --bail --reporter=dots"
