[tools]
biome = "2.5.14"
bun = "1.4.2"
cocogitto = "7.0.0"
lefthook = "2.1.14"
pulumi = "3.263.0"

[hooks]
postinstall = "mise run postinstall-hook"

[env]
_.path = ["./node_modules/.bin"]

[settings]
disable_backends = ["asdf"]
use_versions_host = false
minimum_release_age = "1d"

[task_config]
includes = ["./.config/tasks"]
