[tools]
bun = "1.4.2"

[hooks]
postinstall = "mise run postinstall-hook"

[env]
_.path = ["./node_modules/.bin"]

[settings]
disable_backends = ["asdf"]
use_versions_host = false
minimum_release_age = "1d"

[task_config]
includes = ["./.config/tasks"]
