name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4

      - run: bun install --frozen-lockfile
      - run: mise typecheck
      - run: mise lint
      - run: mise test-ci

  deploy-railway:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: run-checks
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: distinguished-enjoyment
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4

      - run: mise use railway
      - run: railway up --service=${{ env.SVC_ID }}

  deploy-lambda:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: run-checks
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4

      - run: bun install --frozen-lockfile
      - run: |
          cd infra
          pulumi stack select dev
          pulumi up --yes
